# Generated by Django 5.0.7 on 2025-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ruolo', models.CharField(choices=[('passeggero', 'Passeggero'), ('guidatore', 'Guidatore')], max_length=20)),
            ],
        ),
    ]
